services:
  mongodb:
    image: mongo:6.0
    container_name: utopia-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  generate-object:
    build:
      context: .
      dockerfile: src/utopia/microservice/generate_object/Dockerfile
    env_file:
      - .env
    container_name: generate-object-service
    # Other service settings...
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command: 
      uvicorn utopia.microservice.generate_object.generate_object_app_new:app --host 0.0.0.0 --port 8002 --reload

  
  load-user-data:
    build:
      context: .
      dockerfile: src/utopia/microservice/load_user_data/Dockerfile
    env_file:
      - .env
    container_name: load-user-data-service
    # Other service settings...
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
     # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command: 
      uvicorn utopia.microservice.load_user_data.load_user_data_app:app --host 0.0.0.0 --port 8001 --reload
    
  generate-rate-constant:
    build:
      context: .
      dockerfile: src/utopia/microservice/generate_rate_constant/Dockerfile
    env_file:
      - .env
    container_name: generate-rate-constant-service
    depends_on:
      - mongodb
      - generate-object
    ports:
      - "8003:8003"
    # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.generate_rate_constant.generate_rate_constant_app:app --host 0.0.0.0 --port 8003 --reload

  plot-rate-constant:
    build:
      context: .
      dockerfile: src/utopia/microservice/plot_rate_constant/Dockerfile
    env_file:
      - .env
    container_name: plot-rate-constant-service
    depends_on:
      - mongodb
      - generate-rate-constant
    ports:
      - "8004:8004"
    # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.plot_rate_constant.plot_rate_constant_app:app --host 0.0.0.0 --port 8004 --reload
    

  generate-interaction-matrix:
    build:
      context: .
      dockerfile: src/utopia/microservice/generate_interaction_matrix/Dockerfile
    env_file:
      - .env
    container_name: generate-interaction-matrix-service
    depends_on:
      - mongodb
      - generate-rate-constant
    ports:
      - "8005:8005"
    # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.generate_interaction_matrix.fill_interactions_df_app:app --host 0.0.0.0 --port 8005 --reload
  
  solve-steady-state:
    build:
      context: .
      dockerfile: src/utopia/microservice/solve_steady_state/Dockerfile
    env_file:
        - .env
    container_name: solve-steady-state-service
    depends_on:
      - mongodb
      - generate-interaction-matrix
    ports:
      - "8006:8006"
    # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.solve_steady_state.solver_steady_state_app:app --host 0.0.0.0 --port 8006 --reload
  
  estimate-flow:
    build:
      context: .
      dockerfile: src/utopia/microservice/estimate_flow/Dockerfile
    env_file:
        - .env
    container_name: estimate-flow-service
    depends_on:
      - mongodb
      - solve-steady-state
    ports:
      - "8007:8007"
      # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.estimate_flow.estimate_flow_app:app --host 0.0.0.0 --port 8007 --reload

  process-result:
    build:
      context: .
      dockerfile: src/utopia/microservice/process_result/Dockerfile
    env_file:
        - .env
    container_name: process-result-service
    depends_on:
      - mongodb
      - estimate-flow
    ports:
      - "8008:8008"
      # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.process_result.process_result_app:app --host 0.0.0.0 --port 8008 --reload

  plot-fraction-distribution:
    build:
      context: .
      dockerfile: src/utopia/microservice/plot_fraction_distribution/Dockerfile
    env_file:
        - .env
    container_name: plot-fraction-distribution-service
    depends_on:
      - mongodb
      - process-result
    ports:
      - "8009:8009"
      # Development only: mount local code so you can edit and auto-reload
    volumes:
      - ./src:/app/src
    command:
      uvicorn utopia.microservice.plot_fraction_distribution.plot_fraction_distribution_app:app --host 0.0.0.0 --port 8009 --reload

volumes:
  mongo_data: