services:
  mongodb:
    image: mongo:6.0
    container_name: utopia-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  generate-object:
    image: linqianhui/generate-object:${IMAGE_TAG}
    env_file:
      - .env
    container_name: generate-object-service
    depends_on:
      - mongodb
    ports:
      - "8002:8002"

  
  load-user-data:
    image: linqianhui/load-user-data:${IMAGE_TAG}
    env_file:
      - .env
    container_name: load-user-data-service
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8001:8001"

  generate-rate-constant:
    image: linqianhui/generate-rate-constant:${IMAGE_TAG}
    env_file:
      - .env
    container_name: generate-rate-constant-service
    depends_on:
      - mongodb
      - generate-object
    ports:
      - "8003:8003"

  plot-rate-constant:
    image: linqianhui/plot-rate-constant:${IMAGE_TAG}
    env_file:
      - .env
    container_name: plot-rate-constant-service
    depends_on:
      - mongodb
      - generate-rate-constant
    ports:
      - "8004:8004"
  
  generate-interaction-matrix:
    image: linqianhui/generate-interaction-matrix:${IMAGE_TAG}
    env_file:
      - .env
    container_name: generate-interaction-matrix-service
    depends_on:
      - mongodb
      - generate-rate-constant
    ports:
      - "8005:8005"
  
  solve-steady-state:
    image: linqianhui/solve-steady-state:${IMAGE_TAG}
    env_file:
      - .env
    container_name: solve-steady-state-service
    depends_on:
      - mongodb
      - generate-interaction-matrix
    ports:
      - "8006:8006"

  estimate-flow:
    image: linqianhui/estimate-flow:${IMAGE_TAG}
    env_file:
      - .env
    container_name: estimate-flow-service
    depends_on:
      - mongodb
      - solve-steady-state
    ports:
      - "8007:8007"

  process-result:
    image: linqianhui/process-result:${IMAGE_TAG}
    env_file:
      - .env
    container_name: process-result-service
    depends_on:
      - mongodb
      - estimate-flow
    ports:
      - "8008:8008"

  plot-fraction-distribution:
    image: linqianhui/plot-fraction-distribution:${IMAGE_TAG}
    env_file:
      - .env
    container_name: plot-fraction-distribution-service
    depends_on:
      - mongodb
      - process-result
    ports:
      - "8009:8009"

  plot-compartment-distribution:
    image: linqianhui/plot-compartment-distribution:${IMAGE_TAG}
    env_file:
      - .env
    container_name: plot-compartment-distribution-service
    depends_on:
      - mongodb
      - process-result
    ports:
      - "8010:8010"

  calculate-exposure-indicator:
    image: linqianhui/calculate-exposure-indicator:${IMAGE_TAG}
    env_file:
      - .env
    container_name: calculate-exposure-indicator-service
    depends_on:
      - mongodb
      - process-result
    ports:
      - "8011:8011"

volumes:
  mongo_data: